import { emailToolDefs } from '../../routers/emailTools.js';

// ─── Tool definitions (function calling schemas) ───

export const ALL_TOOLS: any[] = [
  { type: 'function', function: { name: 'create_issue', description: 'Create a task/bug/story — an actionable work item on the Kanban board. Use for tracking to-dos, bugs, and feature stories. NOT for reference docs or periodic summaries.', parameters: { type: 'object', properties: { title: { type: 'string', description: 'Issue title' }, type: { type: 'string', enum: ['task','bug','story'], default: 'task' }, priority: { type: 'string', enum: ['low','medium','high','critical'], default: 'medium' }, description: { type: 'string' }, storyPoints: { type: 'number' } }, required: ['title', 'description'] } } },
  { type: 'function', function: { name: 'force_create_issue', description: 'Force-create a task, SKIPPING dedup. Use when user explicitly confirms after seeing duplicate warnings.', parameters: { type: 'object', properties: { title: { type: 'string', description: 'Issue title' }, type: { type: 'string', enum: ['task','bug','story'], default: 'task' }, priority: { type: 'string', enum: ['low','medium','high','critical'], default: 'medium' }, description: { type: 'string', description: 'Detailed description of the bug/feature/task — what needs to be done, why, acceptance criteria' }, storyPoints: { type: 'number' } }, required: ['title', 'description'] } } },
  { type: 'function', function: { name: 'get_stats', description: 'Get project statistics — todo/in-progress/done counts', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'list_issues', description: 'List issues, optionally filtered by status', parameters: { type: 'object', properties: { status: { type: 'string', enum: ['todo','in_progress','in_review','done'] }, limit: { type: 'number', default: 10 } } } } },
  { type: 'function', function: { name: 'get_issue', description: 'Get issue by number (3 for TL-3) or search by title keyword', parameters: { type: 'object', properties: { issueNumber: { type: 'number', description: 'Issue number like 3 for TL-3' }, query: { type: 'string', description: 'Title keyword search' } } } } },
  { type: 'function', function: { name: 'list_notes', description: 'List all knowledge base notes. Optionally filter by query keyword. Returns id, title, category, and content snippet.', parameters: { type: 'object', properties: { query: { type: 'string', description: 'Optional search keyword to filter by title' }, limit: { type: 'number', default: 20 } } } } },
  { type: 'function', function: { name: 'search_notes', description: 'Search knowledge base and notes by semantic similarity', parameters: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } } },
  { type: 'function', function: { name: 'update_issue', description: 'Update an issue. Requires issue number (e.g. 3 for TL-3). Supports title, status, priority, and description.', parameters: { type: 'object', properties: { issueNumber: { type: 'number', description: 'Issue number like 3 for TL-3' }, title: { type: 'string', description: 'New title for the issue' }, status: { type: 'string', enum: ['todo','in_progress','done'] }, priority: { type: 'string', enum: ['low','medium','high','critical'] }, description: { type: 'string', description: 'Updated description (markdown supported). Appended to existing by default. Set append:false to replace entirely.' }, append: { type: 'boolean', description: 'If false, replaces description entirely instead of appending (default: true)' } }, required: ['issueNumber'] } } },
  { type: 'function', function: { name: 'create_report', description: 'Create a report — daily/weekly summaries OR any topic report the user asks for (research, analysis, configuration guides). System auto-checks for duplicates. Use when user says "报告" or "report". NOT for quick notes or wikis — use create_note for those.', parameters: { type: 'object', properties: { reportType: { type: 'string', enum: ['daily','weekly'], default: 'daily' }, title: { type: 'string' }, content: { type: 'string' } }, required: ['title','content'] } } },
  { type: 'function', function: { name: 'update_report', description: 'Update an existing report by ID', parameters: { type: 'object', properties: { id: { type: 'string', description: 'Report ID' }, title: { type: 'string' }, content: { type: 'string' } }, required: ['id'] } } },
  { type: 'function', function: { name: 'create_note', description: 'Create a knowledge base note/wiki page. Use for quick notes, reference docs, meeting minutes, reading notes. System auto-checks for duplicates.', parameters: { type: 'object', properties: { title: { type: 'string' }, content: { type: 'string' }, category: { type: 'string', enum: ['general','architecture','api_docs','todo'] } }, required: ['title'] } } },
  { type: 'function', function: { name: 'update_note', description: 'Update an existing note by ID', parameters: { type: 'object', properties: { id: { type: 'string', description: 'Note ID' }, title: { type: 'string' }, content: { type: 'string' }, category: { type: 'string', enum: ['general','architecture','api_docs','todo'] } }, required: ['id'] } } },
  { type: 'function', function: { name: 'suggest_note_edit', description: 'Fill the note editor form. ONLY works when a note editor is OPEN. Does NOT save to DB — changes appear in chat for user to Apply/Undo. Use when: (1) a blank note form is open to fill it, or (2) an existing note is open AND the user wants to modify it. Check if the request relates to the open note content/title. If unrelated, do NOT modify — ask or use create_note. If editor open but user wants a NEW note, use create_note. If no editor open, use create_note (new) or update_note (by ID).', parameters: { type: 'object', properties: { title: { type: 'string', description: 'Note title' }, content: { type: 'string', description: 'COMPLETE note content - include EVERYTHING. Not just a diff!' }, category: { type: 'string', enum: ['general','architecture','api_docs','runbook'] } }, required: ['content'] } } },
  { type: 'function', function: { name: 'brave_search', description: 'Search via Brave Search API — best for Chinese queries, news, recent info. Use this FIRST for factual queries. If results are poor, try web_search next.', parameters: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } } },
  { type: 'function', function: { name: 'web_search', description: 'Search via Bing + DuckDuckGo — no API key needed. Use as fallback when brave_search returns poor results.', parameters: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } } },
  { type: 'function', function: { name: 'search_local_data', description: 'Search all local data (issues, notes, reports, emails, git commits). Use for any offline lookup.', parameters: { type: 'object', properties: { query: { type: 'string', description: 'Search keywords' } }, required: ['query'] } } },
  { type: 'function', function: { name: 'list_git_commits', description: 'List recent git commits tracked by TomiLite. Returns hash, author, message, timestamp, and stats (files/adds/dels). Use for daily reports ("生成日报") or understanding recent coding activity.', parameters: { type: 'object', properties: { since: { type: 'string', description: 'ISO date prefix (e.g. 2026-07-14), defaults to today' }, limit: { type: 'number', default: 20 } } } } },
  { type: 'function', function: { name: 'list_workspaces', description: 'Get git work directories and repos', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'suggest_issue_edit', description: 'Fill the task editor form. ONLY works when a task editor is OPEN. Does NOT save to DB — changes appear in chat for user to Apply/Undo. Use when: (1) a blank task form is open to fill it, or (2) an existing task is open AND the user wants to modify it. Check if request relates to the open task (title/number/description). If unrelated, do NOT modify — ask or use create_issue. If editor open but user wants a NEW task, use create_issue. If no editor open, use create_issue (new) or update_issue (by issueNumber).', parameters: { type: 'object', properties: { title: { type: 'string' }, description: { type: 'string' }, status: { type: 'string', enum: ['todo','in_progress','in_review','done'] }, priority: { type: 'string', enum: ['low','medium','high','critical'] }, storyPoints: { type: 'number' } }, required: [] } } },
  { type: 'function', function: { name: 'shell_exec', description: 'Execute a READ-ONLY shell command. Only whitelisted: git log/status/diff, ls, cat, grep, find, etc. No writes, no pipes, no redirects.', parameters: { type: 'object', properties: { command: { type: 'string', description: 'Shell command (read-only whitelist only)' }, cwd: { type: 'string', description: 'Working directory (must be in workspace)' } }, required: ['command'] } } },
  { type: 'function', function: { name: 'mcp_call', description: 'Call a tool on a connected MCP server (github, jira, etc.). Token injected server-side - Agent never sees credentials.', parameters: { type: 'object', properties: { server: { type: 'string', description: 'MCP server name' }, tool: { type: 'string', description: 'Tool name' }, args: { type: 'string', description: 'JSON arguments for the tool' } }, required: ['server', 'tool', 'args'] } } },
  ...emailToolDefs,
  { type: 'function', function: { name: 'suggest_report_edit', description: 'Fill the report editor form. ONLY works when a report is OPEN in the editor. Does NOT save to DB — changes appear in chat for user to Apply/Undo. Use when: (1) a blank report form is open to fill it, or (2) an existing report is open AND the user wants to modify it. Check if request relates to the open report title/content. If unrelated, do NOT modify — ask or use create_report. If editor open but user wants a NEW report, use create_report. If no editor open, use create_report.', parameters: { type: 'object', properties: { title: { type: 'string', description: 'Report title' }, content: { type: 'string', description: 'COMPLETE report. Read existing content from user message first, then modify. Keep all existing + add changes.' } }, required: ['content'] } } },
  { type: 'function', function: { name: 'force_create_note', description: 'Force-create a note, SKIPPING dedup. Use when user explicitly confirms after seeing duplicate warnings.', parameters: { type: 'object', properties: { title: { type: 'string' }, content: { type: 'string' }, category: { type: 'string', enum: ['general','architecture','api_docs','todo'] } }, required: ['title'] } } },
  { type: 'function', function: { name: 'force_create_report', description: 'Force-create a report, SKIPPING dedup. Use when user explicitly confirms after seeing duplicate warnings.', parameters: { type: 'object', properties: { reportType: { type: 'string', enum: ['daily','weekly'], default: 'daily' }, title: { type: 'string' }, content: { type: 'string' } }, required: ['title','content'] } } },
  { type: 'function', function: { name: 'get_report', description: 'Get full content of a report by ID. Use list_reports first to find the ID, then use this to read the complete content before editing, polishing, summarizing, or expanding.', parameters: { type: 'object', properties: { id: { type: 'string', description: 'Report ID from list_reports' } }, required: ['id'] } } },
  { type: 'function', function: { name: 'list_reports', description: 'List or search reports. Pass query to search by title/content. Use to find report IDs before editing, exporting, or deleting.', parameters: { type: 'object', properties: { limit: { type: 'number', default: 10 }, query: { type: 'string', description: 'Search keyword — matches title and content' } } } } },
  { type: 'function', function: { name: 'delete_report', description: 'Delete a report by ID. Use list_reports first to find the ID. Use when user asks to remove a report.', parameters: { type: 'object', properties: { id: { type: 'string', description: 'Report ID' } }, required: ['id'] } } },
  { type: 'function', function: { name: 'export_to_excel', description: 'Export data to Excel (.xlsx). First find the report with list_reports, then pass its id as reportId. ALWAYS use a real UUID — never guess or use placeholder text. Also supports noteId and taskFilter.', parameters: { type: 'object', properties: { reportId: { type: 'string', description: 'UUID from list_reports — exports report content' }, noteId: { type: 'string', description: 'Note UUID — exports note content' }, taskFilter: { type: 'string', description: 'todo, done, or all — exports task list' }, rows: { type: 'string', description: 'JSON array of row objects (last resort)' }, filename: { type: 'string', description: 'Optional filename' } }, required: [] } } },
  { type: 'function', function: { name: 'export_to_doc', description: 'Export content to Word (.docx). Use reportId (UUID) for reports, noteId for notes, taskFilter ("todo"/"done"/"all") for tasks, content (markdown) for custom text. Prefer reportId/noteId/taskFilter over content — they read from DB.', parameters: { type: 'object', properties: { reportId: { type: 'string', description: 'UUID from list_reports' }, noteId: { type: 'string', description: 'Note UUID' }, taskFilter: { type: 'string', description: 'todo, done, or all' }, content: { type: 'string', description: 'Markdown content (last resort)' }, filename: { type: 'string', description: 'Optional filename' } }, required: [] } } },

  // ─── Report Editor Tools (called when report editor is open) ───
  { type: 'function', function: { name: 'polish_report', description: 'POLISH the report content in the open report editor. Improve clarity, flow, grammar, and professionalism. Keep all existing content and structure — enhance quality without removing information. Use suggest_report_edit to apply changes. Steps: (1) Read the report content from the user context (2) Polish: fix grammar, improve phrasing, enhance professionalism (3) Call suggest_report_edit with the polished content.', parameters: { type: 'object', properties: { content: { type: 'string', description: 'COMPLETE polished report content — include everything, not just changes' } }, required: ['content'] } } },
  { type: 'function', function: { name: 'summarize_report', description: 'SUMMARIZE the report into key bullet points. Extract the most important information into 3-5 concise bullet points. Keep all critical data (numbers, dates, key decisions). Use suggest_report_edit to apply. Steps: (1) Read the report content (2) Identify key points (3) Rewrite as concise bullet format (4) Call suggest_report_edit.', parameters: { type: 'object', properties: { content: { type: 'string', description: 'Summarized report in bullet-point format' } }, required: ['content'] } } },
  { type: 'function', function: { name: 'expand_report', description: 'EXPAND the report with more detail, context, and depth. Add explanations, examples, implications, and next steps where appropriate. Keep all original content. Use suggest_report_edit to apply. Steps: (1) Read the report content (2) Identify sections that can be expanded (3) Add detail, context, examples (4) Call suggest_report_edit with the expanded content.', parameters: { type: 'object', properties: { content: { type: 'string', description: 'Expanded report with added detail and depth' } }, required: ['content'] } } },
  { type: 'function', function: { name: 'translate_report', description: 'TRANSLATE the report to another language. CRITICAL: targetLanguage is REQUIRED — you MUST ask the user which language BEFORE calling this tool. Never guess.', parameters: { type: 'object', properties: { targetLanguage: { type: 'string', description: 'User-confirmed target language, e.g. "English", "Chinese", "Japanese"' }, content: { type: 'string', description: 'COMPLETE translated report content' }, title: { type: 'string', description: 'Translated title' } }, required: ['targetLanguage', 'content', 'title'] } } },
];

// ─── Pruning ───

export const CORE_TOOLS = ['get_stats', 'list_issues', 'get_issue', 'brave_search', 'web_search', 'shell_exec', 'mcp_call', 'list_workspaces', 'search_local_data'];

export function isCore(name: string): boolean {
  return CORE_TOOLS.includes(name);
}

export interface PruningContext {
  noteEditorOpen: boolean;
  taskEditorOpen: boolean;
  newTaskFormOpen: boolean;
  reportEditorOpen: boolean;
  isQwen: boolean;
}

/** Prune suggest_*_edit tools based on which editor is open. Removes web_search for Qwen (uses native enable_search). */
export function getActiveTools(tools: any[], context: PruningContext): any[] {
  let active = tools;
  if (context.noteEditorOpen) {
    active = active.filter((t: any) => t.function.name !== 'suggest_issue_edit' && t.function.name !== 'suggest_report_edit');
  } else if (context.taskEditorOpen || context.newTaskFormOpen) {
    active = active.filter((t: any) => t.function.name !== 'suggest_note_edit' && t.function.name !== 'suggest_report_edit');
  } else if (context.reportEditorOpen) {
    active = active.filter((t: any) => t.function.name !== 'suggest_note_edit' && t.function.name !== 'suggest_issue_edit');
  }
  if (context.isQwen) {
    active = active.filter((t: any) => t.function.name !== 'web_search');
  }
  return active;
}

// ─── Tool labels (for UI display) ───

export const toolLabels: Record<string, string> = {
  search_notes: 'Searching knowledge base', web_search: 'Searching the web',
  create_issue: 'Creating issue', force_create_issue: 'Force-creating issue', get_stats: 'Fetching stats',
  list_issues: 'Listing issues', get_issue: 'Looking up issue', update_issue: 'Updating issue',
  suggest_note_edit: 'Generating suggestion', create_note: 'Creating note', force_create_note: 'Force-creating note',
  create_report: 'Creating report', force_create_report: 'Force-creating report',
  search_local_data: 'Searching local data', list_workspaces: 'Listing workspaces', shell_exec: 'Running command', mcp_call: 'Calling external tool',
  list_reports: 'Listing reports', export_to_excel: 'Exporting to Excel', export_to_doc: 'Exporting to Word',
};
